services:
  server:
    container_name: tf-server
    depends_on:
      - database
    image: tf-server:latest
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .${SLASH}src:/usr/src/app/src
      - .${SLASH}tsconfig.json:/usr/src/app/tsconfig.json
      - .${SLASH}package.json:/usr/src/app/package.json
      - .${SLASH}.swcrc:/usr/src/app/.swcrc
      - .${SLASH}start.sh:/usr/src/app/start.sh
    command: /bin/sh -c "./start.sh"
    # labels:
    #   - 'autoheal=true'
    # restart: always
    # healthcheck:
    #   test: curl --fail http://localhost:8080 || exit 1
    #   interval: 10s
    #   timeout: 5s
    #   retries: 1
    #   start_period: 60s

  database:
    container_name: tf-database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: database
    command: -p 5432
    ports:
      - '5432:5432'
    volumes:
      - .${SLASH}volumes${SLASH}postgres:/var/lib/postgresql/data

  # autoheal:
  #   image: willfarrell/autoheal:latest
  #   tty: true
  #   restart: always
  #   environment:
  #     - AUTOHEAL_INTERVAL=15
  #     - AUTOHEAL_START_PERIOD=300
  #     - AUTOHEAL_DEFAULT_STOP_TIMEOUT=2
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
